//
//  Icons.swift
//  QRCodeReaderApp
//
//  Created by Eliezer Rodrigo Beltramin de Sant Ana on 04/12/23.
//

import UIKit

/// Enum que contém todos os casos de ícones, ao selecionar um caso ele retorna o unicode desde ícone.

public enum Icons: String, CaseIterable {
    case _24h
    case _3DotsHorizontal
    case _3DotsVertical
    case Academy
    case Accelerator
    case Accessibility
    case AccountBonusDollar
    case AccountBonusEuro
    case AccountBonusPound
    case AccountDollar
    case AccountEuro
    case AccountGroupDollar
    case AccountGroupEuro
    case AccountGroupPound
    case AccountManagementDollar
    case AccountManagementEuro
    case AccountManagementPound
    case AccountPeople
    case AccountPound
    case AccountSearchDollar
    case AccountSearchEuro
    case AccountSearchPound
    case AccountUser
    case Add_1px
    case AddInACircle
    case AddPhoto
    case AddToCalendar
    case Add
    case Aesthetics
    case AgileCoach_2
    case AgileCoach
    case Agile
    case Agribusiness
    case AgricultureWorkers
    case Alert
    case AlphabeticalOrder
    case Ambulance
    case American
    case Analysis
    case Ant
    case Antenna
    case AppSantander
    case AppleOutline
    case Appliances
    case Appointments
    case ArrowDown
    case ArrowLeft
    case ArrowRight
    case ArrowUp
    case AssistedNavigation
    case Associations
    case At
    case AtmDollar
    case AtmEuro
    case AtmPound
    case Atm
    case Atom
    case AttachDocument
    case Attachment
    case Auction
    case AudioOff
    case AudioOn
    case Authentication
    case Awards
    case Backlog
    case BagOfMoneyDollar
    case BagOfMoneyEuro
    case BagOfMoneyPound
    case BankFees
    case Barcode
    case Basket
    case Bath
    case BathroomAlt
    case Bathroom
    case Bbq
    case Beach
    case BecomeNewClient
    case Bed
    case Bell
    case Benefitiary
    case Bike
    case Blink
    case BlockInACircle
    case BoatTrip
    case Bodybuilding
    case Book
    case BookletAtmEnter
    case BookletAtmWithdraw
    case Bookmark
    case BrokerPlataform
    case Brush
    case Bug
    case Building
    case BurgerMenu_1px
    case BurgerMenu
    case Burndowncharct
    case Burndownchart2
    case BusinessAlert
    case BusinessStore
    case BusinessSupport
    case Calculator
    case Calendar
    case CallCenterDb
    case CallSupport
    case Camera
    case CampingGas
    case CancelAppointments
    case CancelCheck
    case CancelCheckbook
    case CancelNextReceipt
    case Capitalization
    case CardBlock
    case CardEnterECash
    case CardExtract
    case CardInsert
    case CardInvoice
    case CardMachine
    case CardPostponeLiquidation
    case Card
    case CardboardBox
    case Cards
    case CarnivorousFood
    case CenterPosition
    case ChampionsLeague
    case ChangeAccountAssociateDollar
    case ChangeAccountAssociateEuro
    case ChangeAccountAssociatePound
    case ChangeBeneficiary
    case ChangeContributions
    case ChatBot
    case Chat
    case CheckAsigment
    case Check
    case Checkbook
    case CheckingAccountChange
    case CheckingAccountClosing
    case CheckingAccountOpen
    case CheckingAccount
    case Checklist
    case CheckmarkInACircle
    case Checkmark
    case Chemistry
    case ChevronDown_1px
    case ChevronDownSmall_1px
    case ChevronDownSmall
    case ChevronDown
    case ChevronLeft_1px
    case ChevronLeftSmall_1px
    case ChevronLeftSmall
    case ChevronLeft
    case ChevronRight_1px
    case ChevronRightSmall_1px
    case ChevronRightSmall
    case ChevronRight
    case ChevronUp_1px
    case ChevronUpSmall_1px
    case ChevronUpSmall
    case ChevronUp
    case Children
    case Cinema
    case CircleAccountAddUser
    case CircleAccountUser
    case Circuit
    case City
    case CivilLiability
    case Clean
    case Clients
    case Clip
    case Clipboard
    case ClockOut
    case ClockRestart
    case Close_1px
    case Close
    case Cloud
    case Cloudy
    case CodeWindow
    case CollapseKeyboard
    case Commerce
    case Commodities
    case CommunicationAnnouncement
    case CommunicationMessage
    case CompanyRadar
    case ConfirmingAdvancesDollar
    case ConfirmingAdvancesEuro
    case ConfirmingAdvancesPound
    case Contacless
    case Contacts
    case Control
    case CoordinatesCard
    case Copy
    case Correct
    case Countryside
    case Credit
    case CvvNumber
    case Daily
    case DayTimeChange
    case DealHandshake
    case Dealership
    case Death
    case Debt
    case DeferredTransfer
    case DefinitionOfDone
    case DefinitionOfReady
    case DeleteAccount
    case Delivery
    case DepositCheck
    case Deposits
    case Desktop
    case Diamond
    case Dice
    case DigitalChannels
    case DigitalSubscriptionsCards
    case DigitalSubscriptionsContactless
    case DigitalSubscriptions
    case DirectMoney
    case Dirty
    case DiscountCard
    case Discount
    case Dna
    case Doctor
    case DocumentBdr
    case DocumentCv
    case DocumentDoc
    case DocumentEtf
    case DocumentPdf
    case DocumentPng
    case DocumentPpt
    case DocumentSketch
    case DocumentSvg
    case DocumentTxt
    case DocumentXls
    case Document
    case DollarBill
    case DollarSymbol
    case DomesticService
    case DoubleTap
    case DownloadFromCloud
    case Download
    case Dragndrop
    case DuplicatedReceipt
    case Dynamics
    case E_
    case ECard
    case ECash
    case EditTransfer
    case Edit
    case ElectricBike
    case ElectricCar
    case EmailInvoiceDollar
    case EmailInvoiceEuro
    case EmailInvoicePound
    case Email
    case EmojiAngry
    case EmojiHappy
    case EmojiKiss
    case EmojiNeutral
    case EmojiReisedEyebrow
    case EmojiSad
    case Employees
    case Energy
    case EnterFullscreen
    case EnterMoneyAtm
    case EnterPin
    case EntertainmentLeisure
    case Entrepreneurship
    case EolicEnergy
    case Epic
    case Error_400_500
    case Error
    case Estimation
    case EuroBillNote
    case EuroSymbol
    case Exhange
    case ExitFullscreen
    case FaceIdApple
    case FaceId
    case FacebookOutline
    case Facebook
    case FactoringDollar
    case FactoringEuro
    case FactoringPound
    case Factoring
    case Factory
    case Family
    case Faq
    case Fashion
    case Fatca
    case Featured
    case FileTransfer
    case File
    case FilterDeactivate
    case Filter
    case FinancePurchaseDollar
    case FinancePurchaseEuro
    case FinancePurchasePound
    case FinancialIndicator
    case FinancialManager
    case Financing
    case Finger
    case Fire
    case Firewall
    case Fishermen
    case FixedExpenses
    case Flag
    case Fog
    case Folder
    case FontAdjust
    case FontSizeDecrease
    case FontSizeIncrease
    case ForeignTrade
    case Fragile
    case Franchise
    case Fraud
    case FreeWiFi
    case FullScreen_2
    case FullScreenExit
    case FullScreen
    case Furniture
    case Gale
    case GasStation
    case GetMoneyAtmCode
    case GetPinNumber
    case GetYourKey
    case Ghost
    case GiftCard
    case GiftTicket
    case Gift
    case Gold
    case Golf
    case GooglePlayOutline
    case HairStylist
    case Hammer
    case Handqr
    case HealthCheck
    case HealthInsurance
    case Heart
    case HelpInACircle
    case HelpUsToImprove
    case Help
    case HiContrast
    case HighlightedServices
    case Highway
    case History
    case Home
    case Hospital
    case Housing
    case IdCard
    case Idea
    case ImageUnavailable
    case Image
    case Inbox
    case IncomeExpenses
    case IncomeTax
    case IncomeTaxes
    case Incomplete
    case Increase2
    case IndustryWorkers
    case InformationInACircle
    case Input
    case Inspection
    case InstagramOutline
    case Instagram
    case Insurance
    case InternationalFinancing
    case International
    case InvestmentSmallCaps
    case InvestmentTeam
    case Investment
    case KeepYourDistance
    case Key
    case King
    case Lake
    case Lamp
    case Language
    case Laptop
    case LegalDocument
    case LevyReceivedDollar
    case LevyReceivedEuro
    case LevyReceivedPound
    case LevySentDollar
    case LevySentEuro
    case LevySentPound
    case LifeSaver
    case LifeShow
    case Lightening
    case Lighthouse
    case Link
    case LinkedinOutline
    case Linkedin
    case Liquidation
    case List
    case LocalCommerce
    case LocationActive
    case Location
    case Lockout
    case LoyaltyCard
    case Luggage
    case Magnet
    case Maintenance
    case ManagementHealth
    case Management
    case Marternity
    case Maternity
    case Medal
    case MediumLongTermFinancing
    case MicOff
    case MicOn
    case Mic
    case Minimise_1px
    case Minimise
    case MinusInACircle
    case Miscellaneous
    case MobileChart
    case MobileLandscape
    case MobileMessage
    case MobilePayment
    case MobileTopUp
    case Mobile
    case ModifyLiquidationMethod
    case MoneyCashDollar
    case MoneyCashEuro
    case MoneyCashPound
    case MoonClouds
    case Moon
    case MoreInACircle
    case Mortgage
    case MortgagesDollar
    case MortgagesEuro
    case MortgagesPound
    case MotorSports
    case Motorbike
    case Mountains
    case MouseMuseum
    case Music
    case Nail
    case NetworkShare
    case NewAccount
    case Newspaper
    case NfcBracelet
    case NfcSticker
    case Nfc
    case NoMessages
    case NoTransactions
    case NonSupportedBrowser
    case NowLogo
    case Now
    case Nut
    case Nutritional
    case OfferDiscount
    case OfficeWorkers
    case OldVersion
    case OneTimePaymentDollar
    case OneTimePaymentEuro
    case OneTimePaymentPound
    case OnlineBanking
    case OnlineTrading
    case OnlineValueDollar
    case OnlineValueEuro
    case OnlineValuePound
    case OperabilityLevel
    case OperateWithoutCard
    case Orthdontics
    case OtherExpenses
    case Others
    case Owl
    case Pacman
    case Party
    case Passport
    case PasswordTyping
    case PaymentDollar
    case PaymentEuro
    case PaymentInProgressDollar
    case PaymentInProgressEuro
    case PaymentInProgressPound
    case PaymentPound
    case PaysheetDollar
    case PaysheetEuro
    case PaysheetPound
    case Percent
    case PeriodicTransfer
    case PeriodicalInput
    case PersonalManager
    case PetrolTower
    case PettyCash
    case Phising
    case Phone_24h
    case PhoneCall
    case PhoneSupport
    case Phone
    case Pill
    case Pin
    case Pinch
    case Pix
    case PizzaChart
    case Place
    case Placeholder
    case Plane
    case PlayButton
    case Plug
    case Plusless
    case PodcastOutline
    case Popup
    case Portability
    case PortfolioOfValues
    case Position
    case PoundNote
    case PoundSymbol
    case Power
    case Price
    case Print
    case ProductDelivery
    case Productowner
    case PublicTransportation
    case Puzzle
    case QrAdvanced
    case QrCode
    case Queries
    case QuickAppointment
    case Quotations
    case RacketsSports
    case Radar
    case RadioButton
    case Radio
    case RainShower
    case Rain
    case Realestatecredit
    case Realestatevalue
    case ReceiptBills
    case ReceiptManagement
    case Receive
    case RecoverAccessKeys
    case RecurrentPaymentDollar
    case RecurrentPaymentEuro
    case RecurrentPaymentPound
    case Recycling
    case RedemptionDollar
    case RedemptionEuro
    case RedemptionPound
    case ReferAFriend
    case Refinement
    case Reform
    case ReformsDecorations
    case RefreshReloadScreen
    case RejectedReceipts
    case Reload
    case RemittancesDollar
    case RemittancesEuro
    case RemittancesPound
    case Renegotiate
    case Renegotiation
    case Renovation
    case RentingCar
    case RentingHome
    case Reports
    case RequestAppointment
    case RestaurantBar
    case Retail
    case RetirementPlanElderly
    case Retrospective
    case ReturnReceipt
    case Return
    case Ribbon
    case SantanderPlus
    case Santander
    case SavingAccountDollar
    case SavingAccountEuro
    case SavingAccountPound
    case SavingInvestment
    case Savings
    case Scales
    case Scanner
    case SchedulePaymentDollar
    case SchedulePaymentEuro
    case SchedulePaymentPound
    case ScheduleSpendingDollar
    case ScheduleSpendingEuro
    case ScheduleSpendingPound
    case Screwdriver
    case Scroll
    case ScrumMaster
    case Scrum
    case Seafood
    case Search
    case SecurityAdvice
    case SecurityBlock
    case SecurityClose
    case SecurityConfiguration
    case SecurityError
    case SecurityOpen
    case SecurityVerified
    case Security
    case SecurizePayment
    case Selfie
    case Send
    case SepaTransfers
    case Settings
    case Share
    case Shareholders
    case ShortTermFinancing
    case Shower
    case Shuffle
    case SignIn
    case SignLanguage
    case SignOff
    case SignUp
    case SignaturePending
    case SimChipInsert
    case SimChip
    case SinisterCar
    case Sitemap
    case Sky
    case SmartwatchPayment
    case Smartwatch
    case Snow
    case Snowflake
    case Soccer
    case SolarEnergy
    case SolidarityRounding
    case SoundWave
    case Spa
    case Speeches
    case SportsRisk
    case Sports
    case SprintReview
    case Sprint
    case Sprintplaning
    case Stack
    case Star
    case StatementsDollar
    case StatementsEuro
    case StatementsPound
    case StayHome
    case Steps
    case StockExchange
    case Strategy
    case Student
    case SubscriptionModel
    case Subscription
    case Subway
    case Success
    case SunCloud
    case Sunny
    case SupermarketCart
    case Suppliers
    case SustainableServices
    case SwiftCards
    case SwipeDown
    case SwipeLeft
    case SwipeRight
    case SwipeUp
    case Tailor
    case Tampon
    case Tap
    case Taxes
    case TeamInteraction
    case TeamManagament
    case TeamTogether
    case TechnologicalRenting
    case TerminalCode
    case TermsConditions
    case TicketMovie
    case Time
    case Timeout
    case TokenMigration
    case Token
    case Torch
    case TowTruck
    case TradeWhatsapp
    case Trade
    case Train
    case Training
    case Transfer
    case Transitions
    case TrashBin
    case Travel
    case Trophy
    case Truck
    case Tutorial
    case Tv
    case TwitterOutline
    case Twitter
    case TwoDoubleTap
    case TwoTap
    case UnblockCard
    case Unicorn
    case University
    case Update
    case UploadToCloud
    case Upload
    case Urgent
    case Userstory
    case UtilitiesServices
    case ValueDecrease
    case ValueIncrease
    case Value
    case VegetarianFood
    case Velocity
    case Veterinary
    case Videochat
    case Videoconference
    case VideogamesSwitch
    case Videogames
    case VisibilityOff
    case VisibilityOn
    case WaitOutsideTheBranch
    case Wallet
    case WarningInACircle
    case Warning
    case WashYourHands
    case WaterDrop
    case WearAFaceMask
    case Webmotors
    case WhatsappLogo
    case WhatsappOutline
    case Whatsapp
    case WheelchairAccessibility
    case WiFi
    case WindowSuccess
    case WithdrawDollar
    case WithdrawECash
    case WithdrawEuro
    case WithdrawMoneyAtm
    case WithdrawPound
    case WithdrawReceiptAtm
    case Woman
    case YogaRelax
    case YoutubeOutline
    case Youtube
    case ZoomIn
    case ZoomOut
    case StarFilled
    case CircleAttentionFilled
    case CircleCheckFilled
    case CircleCloseFilled
    case CircleHelpFilled
    case CircleInformationFilled
    case UrgentFilled
    case BankingCheckingAccountLink
    case FunctionalManageLink
    case IncomeOutcomeDollar
    case OpenFinance
    case Birthday
    case ChartView
    case CompaniesAdd
    case Received
    case PreviousTransfers
    case CheckUpcomingTransfers
    case GeneralTransfers
    case BarChart
    case CandlestickChart
    case ChevronsUpDown
    case PersonalProtection
    case DigitalPhysical
    case Tips
    case SantanderSx
    case IncomeExpensesFilled
    case ArrowDownFilled
    case ArrowUpFilled
    case DocumentCsv
    case DocumentOfx
    case MobileSmile
    case Cap
    case PixKey
    case Museum
    case SelectGlobal
}

extension Icons {
    var stringValue: String {
        let dado = Data(json.utf8)
        let decoder = JSONDecoder()
        let objetoDecodificado = try! decoder.decode([IconsDataModel].self, from: dado)
        return objetoDecodificado.first { $0.name == self.rawValue }?.code ?? "fatalerror"
    }
}

