
default_platform(:ios)

platform :ios do

  desc "Build"
    lane :build do

        #match(type: "appstore", readonly: true)

        cocoapods
        
        build_app(
            workspace: ENV["WORKSPACE"],
            scheme: ENV["SCHEME"],
            export_options: {
                method: "app-store",
                provisioningProfiles: {
                    ENV["APP_IDENTIFIER"] => ENV["PROFILE_APP_STORE"]
                }
            }
        )
    end

    desc "Upload to Test Flight"
    lane :tf do
    
        build

        # https://docs.fastlane.tools/actions/upload_to_testflight
        upload_to_testflight(
            skip_waiting_for_build_processing: true,
            apple_id: ENV["APP_STORE_CONNECT_APPLE_ID"]
        )
    end

    desc "Incremente build number of the app"
    lane :inc do 
      increment_build_number(xcodeproj: "QRCodeReaderApp.xcodeproj")
    end
end
